#https://docs.travis-ci.com/user/tutorial/
#测试配置
sudo: false
language: java
script: mvn clean package
jdk:
  - openjdk11
# whitelist
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - export TZ=Asia/Shanghai
deploy:
  provider: script
  script: "mvn -Dmaven.test.skip=true  clean package nutzboot:shade nutzboot:war --settings mvn_settings.xml"
  skip_cleanup: true
  on:
    tags: false
    branch: master
cache:
  directories:
  - $HOME/.m2
